// <auto-generated>
//     Generated by tools/sync-version.mjs from version.json.
//     Do not edit by hand; run `node tools/sync-version.mjs` after changing version.json.
// </auto-generated>

namespace SmallBasic.Vsix
{
    /// <summary>Product version shared by the Visual Studio and VS Code extensions.</summary>
    public static class SmallBasicVersion
    {
        public const string Value = "0.1.8";
    }
}
