// Single source of truth for the version shared by the Visual Studio and
// Visual Studio Code extensions.
//
// The canonical value lives in <repo>/version.json. Every file that must
// contain the version literally (extension manifests, generated C# and the
// README) is derived from it by syncRepositoryVersion().
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));

/** Absolute path of the repository root, i.e. the directory owning version.json. */
export const repositoryRoot = path.resolve(moduleDirectory, "..");

const versionFile = path.join(repositoryRoot, "version.json");

const semanticVersionPattern = /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/;

/** Reads and validates the shared version. Throws when version.json is missing or malformed. */
export function readRepositoryVersion() {
  if (!fs.existsSync(versionFile)) {
    throw new Error(`Shared version file not found: ${versionFile}`);
  }

  const parsed = JSON.parse(fs.readFileSync(versionFile, "utf8"));
  const version = typeof parsed.version === "string" ? parsed.version.trim() : "";
  if (!semanticVersionPattern.test(version)) {
    throw new Error(
      `version.json must declare a semantic version such as "1.2.3"; got ${JSON.stringify(parsed.version)}.`
    );
  }

  return version;
}

/** Writes only when the content actually changed so builds stay incremental. */
function writeIfChanged(absolutePath, content) {
  const existing = fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, "utf8") : null;
  if (existing === content) {
    return false;
  }

  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, "utf8");
  return true;
}

function syncTextFile(relativePath, transform, updated) {
  const absolutePath = path.join(repositoryRoot, relativePath);
  const before = fs.readFileSync(absolutePath, "utf8");
  const after = transform(before);
  if (after !== before && writeIfChanged(absolutePath, after)) {
    updated.push(relativePath);
  }
}

function versionInfoContent(version) {
  return [
    "// <auto-generated>",
    "//     Generated by tools/sync-version.mjs from version.json.",
    "//     Do not edit by hand; run `node tools/sync-version.mjs` after changing version.json.",
    "// </auto-generated>",
    "",
    "namespace SmallBasic.Vsix",
    "{",
    "    /// <summary>Product version shared by the Visual Studio and VS Code extensions.</summary>",
    "    public static class SmallBasicVersion",
    "    {",
    `        public const string Value = "${version}";`,
    "    }",
    "}",
    "",
  ].join("\n");
}

/**
 * Propagates the version declared in version.json to every file that has to
 * embed it literally. Returns the relative paths that were rewritten, so
 * callers can report what changed.
 */
export function syncRepositoryVersion() {
  const version = readRepositoryVersion();
  const updated = [];

  // VS Code extension manifest, read by npm and consumed by vsce.
  syncTextFile(
    "visual_studio_code_plugin/packages/smallbasic-vscode/package.json",
    (content) => content.replace(/^(\s*"version":\s*")[^"]*(")/m, `$1${version}$2`),
    updated
  );

  // The npm workspace lockfile keeps its own copy of the workspace version.
  syncTextFile(
    "visual_studio_code_plugin/package-lock.json",
    (content) =>
      content.replace(
        /("packages\/smallbasic-vscode":\s*\{\s*"name":\s*"[^"]*",\s*"version":\s*")[^"]*(")/,
        `$1${version}$2`
      ),
    updated
  );

  // Visual Studio VSIX manifest, validated by the VSSDK build.
  syncTextFile(
    "visual_studio_plugin/src/SmallBasic.Vsix/source.extension.vsixmanifest",
    (content) => content.replace(/(<Identity\b[^>]*?\bVersion=")[^"]*(")/, `$1${version}$2`),
    updated
  );

  // Visual Studio in-product version shown in Help > About.
  if (
    writeIfChanged(
      path.join(repositoryRoot, "visual_studio_plugin/src/SmallBasic.Vsix/VersionInfo.g.cs"),
      versionInfoContent(version)
    )
  ) {
    updated.push("visual_studio_plugin/src/SmallBasic.Vsix/VersionInfo.g.cs");
  }

  // README documents the packaged VSIX file names.
  syncTextFile(
    "README.md",
    (content) =>
      content
        .replace(/SmallBasic\.VSCode-\d+\.\d+\.\d+\.vsix/g, `SmallBasic.VSCode-${version}.vsix`)
        .replace(/SmallBasic\.Vsix\.\d+\.\d+\.\d+\.vsix/g, `SmallBasic.Vsix.${version}.vsix`),
    updated
  );

  // Tauri desktop Playground. The npm package, the tauri bundle metadata and
  // the Rust crate all carry the shared version, so its installers are named
  // like the extensions (doc 10, §19.1).
  syncTextFile(
    "visual_studio_code_plugin/packages/smallbasic-playground-desktop/package.json",
    (content) => content.replace(/^(\s*"version":\s*")[^"]*(")/m, `$1${version}$2`),
    updated
  );

  syncTextFile(
    "visual_studio_code_plugin/packages/smallbasic-playground-desktop/src-tauri/tauri.conf.json",
    (content) => content.replace(/^(\s*"version":\s*")[^"]*(")/m, `$1${version}$2`),
    updated
  );

  syncTextFile(
    "visual_studio_code_plugin/packages/smallbasic-playground-desktop/src-tauri/Cargo.toml",
    (content) => content.replace(/^(\s*version\s*=\s*")[^"]*(")/m, `$1${version}$2`),
    updated
  );

  // The workspace lockfile keeps a copy of every workspace package version.
  syncTextFile(
    "visual_studio_code_plugin/package-lock.json",
    (content) =>
      content.replace(
        /("packages\/smallbasic-playground-desktop":\s*\{\s*"version":\s*")[^"]*(")/,
        `$1${version}$2`
      ),
    updated
  );

  return { version, updated };
}
