import fs from "node:fs";
import http from "node:http";
import path from "node:path";

/**
 * Static servers used by the webview harness. They reproduce what the extension
 * resource host (a *.vscode-cdn.net origin in vscode.dev) and the web view host
 * provide: CORS enabled responses with correct MIME types, plus the webview
 * document generated by the real `buildWebviewHtml`.
 */

export const pluginRoot = path.resolve(__dirname, "..", "..", "..");
export const extensionPackageRoot = path.join(pluginRoot, "packages", "smallbasic-vscode");
export const stagedPayloadRoot = path.join(extensionPackageRoot, "runhost", "blazor", "wwwroot");
export const repositoryRoot = path.resolve(pluginRoot, "..");
export const builtWebRunHostRoot = path.join(repositoryRoot, "runhost", "web");

const MIME: Record<string, string> = {
  ".br": "application/octet-stream",
  ".css": "text/css; charset=utf-8",
  ".dat": "application/octet-stream",
  ".dll": "application/octet-stream",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".wasm": "application/wasm"
};

export interface StaticServer {
  origin: string;
  close(): Promise<void>;
}

export interface StaticServerOptions {
  /** Enables CORS globally or selectively for a resolved file path. */
  cors?: boolean | ((file: string) => boolean);
}

/** Fails with setup instructions when the Blazor payload was never staged. */
export function requireStagedPayload(): string {
  const entry = path.join(stagedPayloadRoot, "_framework", "blazor.webassembly.js");
  if (!fs.existsSync(entry)) {
    throw new Error(
      `Staged Blazor payload not found: ${entry}\n` +
        "Build and stage it first:\n" +
        "  .\\runhost\\Build-RunHost.ps1\n" +
        "  npm run stage:blazor -w smallbasic-tools-vsc"
    );
  }

  return stagedPayloadRoot;
}

/** Fails with setup instructions when the built static web distribution is missing. */
export function requireBuiltWebRunHost(): string {
  const entry = path.join(builtWebRunHostRoot, "playground.html");
  if (!fs.existsSync(entry)) {
    throw new Error(
      `Built web RunHost not found: ${entry}\n` +
        "Build it first:\n" +
        "  .\\runhost\\Build-RunHost.ps1"
    );
  }

  return builtWebRunHostRoot;
}

/** Serves a folder over HTTP with CORS, mounting it below `mountPath`. */
export async function serveDirectory(
  root: string,
  mountPath = "",
  options: StaticServerOptions = {}
): Promise<StaticServer> {
  const prefix = mountPath.replace(/\/$/, "");

  const server = http.createServer((request, response) => {
    const url = decodeURIComponent((request.url ?? "/").split("?")[0]);
    if (prefix && !url.startsWith(prefix)) {
      response.writeHead(404, corsHeaders(undefined, options)).end("not found");
      return;
    }

    const file = path.resolve(root, url.slice(prefix.length).replace(/^\/+/, ""));
    if (!file.startsWith(path.resolve(root)) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      response.writeHead(404, corsHeaders(file, options)).end("not found");
      return;
    }

    response.writeHead(200, {
      ...corsHeaders(file, options),
      "Cache-Control": "no-store",
      "Content-Length": String(fs.statSync(file).size),
      "Content-Type": MIME[path.extname(file).toLowerCase()] ?? "application/octet-stream"
    });
    fs.createReadStream(file).pipe(response);
  });

  return listen(server);
}

function corsHeaders(file: string | undefined, options: StaticServerOptions): Record<string, string> {
  const enabled = typeof options.cors === "function"
    ? !!file && options.cors(file)
    : options.cors !== false;
  return enabled ? { "Access-Control-Allow-Origin": "*" } : {};
}

/** Serves one fixed HTML document (the webview page). */
export async function serveDocument(html: string): Promise<StaticServer> {
  const server = http.createServer((_request, response) => {
    response.writeHead(200, { "Cache-Control": "no-store", "Content-Type": "text/html; charset=utf-8" });
    response.end(html);
  });

  return listen(server);
}

function listen(server: http.Server): Promise<StaticServer> {
  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      const port = typeof address === "object" && address ? address.port : 0;
      resolve({
        origin: `http://127.0.0.1:${port}`,
        close: () => new Promise((done) => server.close(() => done()))
      });
    });
  });
}
